# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
# ruff: noqa: E402
"""Smoke test for HunyuanImage-3.0 Text-to-Image (T2I) pipeline."""

import sys
from collections.abc import Generator
from pathlib import Path

import pytest
import torch
from PIL import Image

from vllm_omni import Omni
from vllm_omni.inputs.data import OmniDiffusionSamplingParams

MODEL_NAME = "tencent/HunyuanImage-3.0-Instruct"
REPO_ROOT = Path(__file__).resolve().parents[3]
STAGE_CONFIG_PATH = REPO_ROOT / "vllm_omni" / "model_executor" / "stage_configs" / "hunyuan_image3_t2i.yaml"

sys.path.insert(0, str(REPO_ROOT / "examples" / "offline_inference" / "hunyuan_image3"))
from end2end import build_prompt

pytestmark = [pytest.mark.advanced_model, pytest.mark.diffusion]


@pytest.fixture(scope="module")
def omni() -> Generator[Omni, None, None]:
    engine = Omni(
        model=MODEL_NAME,
        stage_configs_path=str(STAGE_CONFIG_PATH),
        stage_init_timeout=600,
        init_timeout=900,
    )
    try:
        yield engine
    finally:
        engine.close()


@pytest.mark.skipif(torch.cuda.device_count() < 4, reason="Need at least 4 CUDA GPUs.")
def test_t2i_generates_image(omni: Omni) -> None:
    """Verify that the T2I pipeline produces a PIL Image output."""
    sampling_params = OmniDiffusionSamplingParams(
        seed=1234,
        num_outputs_per_prompt=1,
    )

    prompt = build_prompt(
        "A brown and white dog is running on the grass",
        task="t2i_think",
    )

    outputs = omni.generate(
        {"prompt": prompt, "modalities": ["image"]},
        sampling_params,
    )
    assert outputs, "No outputs returned from Omni.generate()"

    first_output = outputs[0]
    images = getattr(first_output, "images", None)
    if images is None:
        request_output = getattr(first_output, "request_output", None)
        assert request_output is not None, "No request_output in Omni output"
        images = getattr(request_output, "images", None)

    assert images and len(images) > 0, "No image was generated by the T2I pipeline"
    assert isinstance(images[0], Image.Image), f"Expected PIL Image, got {type(images[0])}"
    assert images[0].size[0] > 0 and images[0].size[1] > 0, "Generated image has zero dimensions"
