# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""Smoke test for HunyuanImage-3.0 Image+Text-to-Image (IT2I) pipeline."""

from collections.abc import Generator
from pathlib import Path

import pytest
import torch
from PIL import Image

from vllm_omni import Omni

MODEL_NAME = "tencent/HunyuanImage-3.0-Instruct"
REPO_ROOT = Path(__file__).resolve().parents[3]
STAGE_CONFIG_PATH = REPO_ROOT / "vllm_omni" / "model_executor" / "stage_configs" / "hunyuan_image3_it2i.yaml"

pytestmark = [pytest.mark.advanced_model, pytest.mark.diffusion]


@pytest.fixture(scope="module")
def omni() -> Generator[Omni, None, None]:
    engine = Omni(
        model=MODEL_NAME,
        stage_configs_path=str(STAGE_CONFIG_PATH),
        stage_init_timeout=600,
        init_timeout=900,
    )
    try:
        yield engine
    finally:
        engine.close()


def _extract_generated_image(outputs: list[object]) -> Image.Image:
    """Extract the first generated image from Omni outputs."""
    if not outputs:
        raise AssertionError("No outputs were returned from Omni.generate()")

    first_output = outputs[0]
    if images := getattr(first_output, "images", None):
        return images[0]

    request_output = getattr(first_output, "request_output", None)
    if request_output is not None and (images := getattr(request_output, "images", None)):
        return images[0]

    # Try py_generator style output
    if hasattr(first_output, "final_output_type") and first_output.final_output_type == "image":
        ro = first_output.request_output
        if images := getattr(ro, "images", None):
            return images[0]
        if mm := getattr(ro, "multimodal_output", None):
            if isinstance(mm, dict) and (imgs := mm.get("images")):
                return imgs[0]

    raise AssertionError("No generated image found in Omni output")


@pytest.mark.skipif(torch.cuda.device_count() < 8, reason="Need at least 8 CUDA GPUs.")
def test_it2i_generates_image(omni: Omni) -> None:
    """Verify that the IT2I pipeline produces a PIL Image output."""
    # Use a simple solid-color image as input (no external file dependency)
    input_image = Image.new("RGB", (512, 512), color=(200, 100, 50))

    prompt = (
        "<|startoftext|>You are an advanced multimodal model whose core "
        "mission is to analyze user intent and generate high-quality text "
        "and images.<img><think>Change the color to bright blue."
    )
    prompt_dict = {
        "prompt": prompt,
        "modalities": ["image"],
        "multi_modal_data": {"image": input_image},
        "height": 512,
        "width": 512,
    }

    # Use py_generator to handle multi-stage output
    final_image = None
    for stage_outputs in omni.generate(prompts=[prompt_dict], py_generator=True):
        if stage_outputs.final_output_type == "image":
            output = stage_outputs.request_output
            images = getattr(output, "images", None) or []
            if not images and hasattr(output, "multimodal_output"):
                images = output.multimodal_output.get("images", [])
            if images:
                final_image = images[0]

    assert final_image is not None, "No image was generated by the IT2I pipeline"
    assert isinstance(final_image, Image.Image), f"Expected PIL Image, got {type(final_image)}"
    assert final_image.size[0] > 0 and final_image.size[1] > 0, "Generated image has zero dimensions"
